name: kiss_dynamodb_repository
description: "A DynamoDB implementation of kiss_repository interface"
version: 0.1.0
homepage: https://github.com/WAMF/kiss_dynamodb_repository

environment:
  sdk: ^3.8.0

dependencies:
  document_client: ^2.0.0           # Primary DynamoDB interface
  aws_dynamodb_api: ^2.0.0          # Low-level AWS API client
  shared_aws_api: ^2.0.0            # AWS shared utilities
  uuid: ^4.5.1                      # UUID generation for auto-identification
  
  kiss_repository: ^0.11.0

dev_dependencies:
  test: ^1.24.0
  very_good_analysis: ^6.0.0
  kiss_repository_tests: ^0.1.0
