name: kiss_dynamodb_repository
description: "A DynamoDB implementation of kiss_repository interface"
version: 0.1.0
homepage: https://github.com/WAMF/kiss_dynamodb_repository

environment:
  sdk: ^3.8.0

dependencies:
  document_client: ^2.0.0           # Primary DynamoDB interface
  aws_dynamodb_api: ^2.0.0          # Low-level AWS API client
  shared_aws_api: ^2.0.0            # AWS shared utilities
  
  kiss_repository:
    path: ../kiss_repository

dev_dependencies:
  test: ^1.24.0
  lints: ^5.0.0
