version: '3.8'
services:
  dynamodb-local:
    image: "amazon/dynamodb-local:2.5.2"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "../docker/dynamodb:/home/dynamodblocal/data"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data -disableTelemetry"
    working_dir: /home/dynamodblocal 